### ISSUE TITLE
Using dtocean-electrical in DTOceanPlus

### ISSUE THREAD

**Issue by anupjn** [DTOcean/dtocean-electrical#13]
Hi @H0R5E Mathew, I am developing the energy delivery module for the DTOceanPlus project and my original plan was to use the dtocean-electrical module in DTO2 as the base to start from. Can you please let me know if my thinking on this is correct? 

We will be extending existing functionalities and adding some new functionalities to the DTO2 dtocean-electrical tool. A, possibly major, difference is that we will be using Python 3.7. Can you please comment on how easy/hard converting code written in Pythono 2.7 to 3.7 might be? 

Considering all the delicate dependencies DTO2 dtocean-electrical has (from the discussion we have had recently) can you please suggest the best way to approach using dtocean-electrical as the base for DTOPlus? Any tips and tricks and suggestions from you would be deeply appreciated.  

Thank you, in advance, for your time and help on this.

**Comment by anupjn** [comment]
Hi, I managed to get the dtocean-electrical module run on Python 3 and with newer versions of the different packages installed. It thankfully turned out to be a relatively more straightforward process than what I had expected, thanks to the way it was coded in the first place, I guess.

**Comment by H0R5E** [comment]
Hi Anup,

You put a lot of questions into there, so I have been thinking about how to reply. I'm afraid I can't really offer any useful advice regarding the appropriateness or otherwise of this module for use in DTOcean+. I can, however, discuss upgrading this module in the context of the existing DTOcean suite.

It's good that you managed to get it operating using Python 3. A lot of the dependency issues relate to still using Python 2 (and therefore Qt4 rather than Qt5) in the other modules. Upgrading the whole suite to Python 3 and Qt5 would certainly be useful for increasing the longevity of this version of DTOcean.

The problem is finding (and funding) the time to convert all of the modules and to test if the task has been successful. The problem lies in the low test coverage of the modules  (25% for this one), so although you may have a subset of the code working correctly in Python 3, its hard to guarantee that everything is working. Ultimately, better unit test coverage should be one of your priorities for future updates to verify that your changes have worked.

I'd be interested in incorporating your Python 3 update into this repository, if you are interested. If you create a pull request, I will create a new "experimental" branch to store it. Note, it is important that there are no changes to the inputs, outputs & functionality, unless they have been approved for use within the other modules beforehand. This is to ensure that the upgrade is useful to _this_ version of DTOcean.
